apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-mongo-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders-mongo
  template:
    metadata:
      labels:
        app: orders-mongo
    spec:
      containers:
        - name: orders-mongo
          image: mongo
          resources:
            limits:
              memory: {{.Values.mongoDB.resources.limits.memory}}
              cpu: {{.Values.mongoDB.resources.limits.cpu}}
          ports:
            - containerPort: {{.Values.mongoDB.port}}
---
apiVersion: v1
kind: Service
metadata:
  name: orders-mongo-srv
spec:
  selector:
    app: orders-mongo
  ports:
    - port: {{.Values.mongoDB.port}}
      targetPort: {{.Values.mongoDB.port}}
