apiVersion: apps/v1
kind: Deployment
{{ $serviceName:= "tickets"}}
metadata:
  name: {{$serviceName}}-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{$serviceName}}
  template:
    metadata:
      labels:
        app: {{$serviceName}}
    spec:
      containers:
        - name: {{$serviceName}}
          image: {{.Values.ticketsImageKey.repository}}:{{.Values.ticketsImageKey.tag}}
          imagePullPolicy: {{.Values.ticketsImageKey.pullPolicy}}
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: ticketing
            - name: MONGO_URI
              value: 'mongodb://tickets-mongo-srv:{{.Values.mongoDB.port}}/tickets'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
          resources:
            limits:
              memory: {{.Values.resources.limits.memory}}
              cpu: {{.Values.resources.limits.cpu}}
          ports:
            - containerPort: {{.Values.appServicePort}}
---
apiVersion: v1
kind: Service
metadata:
  name: tickets-srv
spec:
  selector:
    app: {{$serviceName}}
  ports:
    - port: {{.Values.appServicePort}}
      targetPort: {{.Values.appServicePort}}
