name: tests-orders

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'orders/**'
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd orders && npm install && npm run test:ci
